-- CreateTable
CREATE TABLE "campaign_screen_settings" (
    "id" SERIAL NOT NULL,
    "campaign_id" INTEGER NOT NULL,
    "amount_big_screen" INTEGER,
    "display_top_part" BOOLEAN NOT NULL DEFAULT TRUE,
    "display_bottom_part" BOOLEAN NOT NULL DEFAULT TRUE,
    "preloading_names" BOOLEAN NOT NULL DEFAULT TRUE,
    "by_presence" BOOLEAN NOT NULL DEFAULT FALSE,
    "text_over_total" TEXT,
    "text_under_total" TEXT,
    "bg_screen" TEXT,
    "bg_big_donations" TEXT,
    "has_goal" BOOLEAN,
    "name_vs_phone" INTEGER,
    "top_part_bottom_titles_color" TEXT,
    "text_video" TEXT,
    "font_size_text_video" INTEGER,
    "video_date" TIMESTAMP(3),
    "video_repeat" INTEGER,
    "video_url" TEXT,
    "top_timer_text" TEXT,
    "bottom_timer_text" TEXT,
    "cube_width" INTEGER,
    "cube_hight" INTEGER,
    "cube_padding" INTEGER,
    "border_radius" INTEGER,
    "font_size_name_front" INTEGER,
    "font_size_name_back" INTEGER,
    "font_size_amount_back" INTEGER,
    "display_rank" BOOLEAN,
    "font_size_rank" INTEGER,
    "display_free_field1" BOOLEAN,
    "font_size_free_field1" INTEGER,
    "front_box_text_color" TEXT,
    "back_box_text_color" TEXT,
    "show_amount" BOOLEAN,
    "bs_show_logo" BOOLEAN,
    "bs_logo_height" INTEGER,
    "bs_logo_top_margin" INTEGER,
    "bs_name_font_size" INTEGER,
    "bs_name_color" TEXT,
    "bs_name_top_margin" INTEGER,
    "bs_show_amount" BOOLEAN,
    "bs_amount_font_size" INTEGER,
    "bs_amount_color" TEXT,
    "bs_amount_top_margin" INTEGER,
    "bs_show_rank" BOOLEAN,
    "bs_rank_font_size" INTEGER,
    "bs_rank_color" TEXT,
    "bs_rank_top_margin" INTEGER,
    "show_names_in_donation_screen" BOOLEAN,
    "display_donation_button" BOOLEAN,
    "donation_button_position" TEXT,
    "donation_button_background_image" TEXT,
    "donation_button_url" TEXT,
    "title_before" TEXT,
    "has_shop" BOOLEAN,
    "minimum_cart" INTEGER,
    "charge_method_id" INTEGER,
    "nedarim_mosad" TEXT,
    "nedarim_api_valid" BOOLEAN,
    "shop_phone" TEXT,
    "if_hok" BOOLEAN,
    "if_fund_raiser" BOOLEAN,
    "show_sum" BOOLEAN,
    "show_donor_fund_raiser" BOOLEAN,
    "mosad_webhook1" INTEGER,
    "mosad_webhook2" INTEGER,
    "mosad_webhook3" INTEGER,
    "skip_donation_approved" BOOLEAN,
    "supervisor_approval" BOOLEAN,
    "created_at" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "campaign_screen_settings_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "campaign_screen_settings_campaign_id_key" UNIQUE ("campaign_id")
);

-- AddForeignKey
ALTER TABLE "campaign_screen_settings" ADD CONSTRAINT "campaign_screen_settings_campaign_id_fkey" FOREIGN KEY ("campaign_id") REFERENCES "campaigns"("id") ON DELETE RESTRICT ON UPDATE CASCADE;


